[workspace]
resolver = "3"
members = [
    "services/api",
]

[workspace.package]
edition = "2024"
version = "0.0.1" 

[profile.release]
debug = false
strip = true
opt-level = 3
lto = true
codegen-units = 1